spring:
  profiles:
    active: dev
  application:
    name: epam-gym-app-trainer-workload-service
  data:
    jpa:
      repositories:
        enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}
server:
  port: 8081