spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/epam_gym_app_main_service
    driver-class-name: org.postgresql.Driver
    username: epam
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      jakarta.persistence.sql-load-script-source: classpath:database_initializer/data.sql
    open-in-view: true

  data:
    jpa:
      repositories:
        enabled: true

application:
  security:
    jwt-token:
      access-expiration: 3600000
      refresh-expiration: 15778800000  #  6 months
      keys:
        secret-key: "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0"

server:
 port: 8080