spring:
  application:
    name: epam-gym-app-trainer-workload-service

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:postgresql://localhost:5434/epam_gym_app_training_service
    driver-class-name: org.h2.Driver
    username: epam
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true

  data:

    jpa:
      repositories:
        enabled: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}
server:
  port: 8081